---
- hosts: web3
  become: yes
  tasks: 
  - name: Install Apache ubuntu
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: Install Apache centOS
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: Start Apache ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
  - name: Start Apache centOS
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"
  - name: writing some content in index.html
    copy:
      content: <h1> Welcome to Apache <h1>
      dest: /var/www/html/index.html
  - name: Install php
    package:
      name: php
      state: present
  - name: update php page 
    copy:
      dest: /var/www/html/
      src: /home/centos/playbooks/date.php
  - name: Restart Apache ubuntu
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"
...
