---
- hosts: web3
  become: yes
  vars:
    username: Arun
    apache_port: 80
  tasks: 
  - name: Install Apache ubuntu
    package:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: Install Apache centOS
    package:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: Start Apache ubuntu
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
  - name: Start Apache centOS
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_os_family == "RedHat"
  - name: Update index page
    copy:
      content: <h1> Welcome to Apache <h1>
      dest: /var/www/html/index.html
  - name: Update Static.html
    copy:
      dest: /var/www/html/static.html
      src: /home/centos/playbooks/static.html
  - name: Update Dynamic.html
    template:
      dest: /var/www/html/dynamic.html
      src: /home/centos/playbooks/dynamic.j2
  - name: Install php
    package:
      name: php
      state: present
  - name: update php page 
    copy:
      dest: /var/www/html/
      src: /home/centos/playbooks/date.php

  - name: Update Apache port number
    template:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.j2
    when: ansible_os_family == "RedHat"

  - name: Update Apache port number
    template:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.j2
    when: ansible_os_family == "RedHat"

  - name: Update Apache port number in ubuntu
    template:
      dest: /etc/apache2/ports.conf
      src: /home/centos/playbooks/ports.j2
    when: ansible_os_family == "Debian"

  - name: Restart Apache ubuntu
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
  - name: Restart Apache RedHat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"
...
