---
- hosts: web3
  become: yes
  tasks: 
  - name: Install Apache
    package:
      name: apache2
      state: present
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
  - name: writing some content in index.html
    copy:
      content: <h1> Welcome to Apache <h1>
      dest: /var/www/html/index.html
  - name: Install php
    package:
      name: php
      state: present
  - name: update php page 
    copy:
      dest: /var/www/html/
      src: /home/centos/playbooks/date.php
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
...
