---
- hosts: web3
  become: yes
  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
  tasks: 
  - name: set se linux to permissive
    selinux:
      policy: targeted
      state: permissive
  - name: Install Apache
    package:
      name: httpd
      state: present
    notify:
      - Start httpd
  - name: writing some content in index.html
    copy:
      content: <h1> Welcome to Apache <h1>
      dest: /var/www/html/index.html
  - name: Update Apache port number
    copy:
      dest: /etc/httpd/conf/httpd.conf
      src: /home/centos/playbooks/httpd.conf
    notify:
      - Restart httpd
  - name: Install php
    package:
      name: php
      state: present
  - name: update php page 
    copy:
      dest: /var/www/html/
      src: /home/centos/playbooks/date.php
    notify:
      - Restart httpd
...
